// All 30 NBA teams with ESPN IDs
// Used to seed the database and as a reference
export const NBA_TEAMS = [
  { name: "Atlanta Hawks", abbreviation: "ATL", espnId: "1", conference: "East" },
  { name: "Boston Celtics", abbreviation: "BOS", espnId: "2", conference: "East" },
  { name: "Brooklyn Nets", abbreviation: "BKN", espnId: "17", conference: "East" },
  { name: "Charlotte Hornets", abbreviation: "CHA", espnId: "30", conference: "East" },
  { name: "Chicago Bulls", abbreviation: "CHI", espnId: "4", conference: "East" },
  { name: "Cleveland Cavaliers", abbreviation: "CLE", espnId: "5", conference: "East" },
  { name: "Dallas Mavericks", abbreviation: "DAL", espnId: "6", conference: "West" },
  { name: "Denver Nuggets", abbreviation: "DEN", espnId: "7", conference: "West" },
  { name: "Detroit Pistons", abbreviation: "DET", espnId: "8", conference: "East" },
  { name: "Golden State Warriors", abbreviation: "GSW", espnId: "9", conference: "West" },
  { name: "Houston Rockets", abbreviation: "HOU", espnId: "10", conference: "West" },
  { name: "Indiana Pacers", abbreviation: "IND", espnId: "11", conference: "East" },
  { name: "LA Clippers", abbreviation: "LAC", espnId: "12", conference: "West" },
  { name: "Los Angeles Lakers", abbreviation: "LAL", espnId: "13", conference: "West" },
  { name: "Memphis Grizzlies", abbreviation: "MEM", espnId: "29", conference: "West" },
  { name: "Miami Heat", abbreviation: "MIA", espnId: "14", conference: "East" },
  { name: "Milwaukee Bucks", abbreviation: "MIL", espnId: "15", conference: "East" },
  { name: "Minnesota Timberwolves", abbreviation: "MIN", espnId: "16", conference: "West" },
  { name: "New Orleans Pelicans", abbreviation: "NOP", espnId: "3", conference: "West" },
  { name: "New York Knicks", abbreviation: "NYK", espnId: "18", conference: "East" },
  { name: "Oklahoma City Thunder", abbreviation: "OKC", espnId: "25", conference: "West" },
  { name: "Orlando Magic", abbreviation: "ORL", espnId: "19", conference: "East" },
  { name: "Philadelphia 76ers", abbreviation: "PHI", espnId: "20", conference: "East" },
  { name: "Phoenix Suns", abbreviation: "PHX", espnId: "21", conference: "West" },
  { name: "Portland Trail Blazers", abbreviation: "POR", espnId: "22", conference: "West" },
  { name: "Sacramento Kings", abbreviation: "SAC", espnId: "23", conference: "West" },
  { name: "San Antonio Spurs", abbreviation: "SAS", espnId: "24", conference: "West" },
  { name: "Toronto Raptors", abbreviation: "TOR", espnId: "28", conference: "East" },
  { name: "Utah Jazz", abbreviation: "UTA", espnId: "26", conference: "West" },
  { name: "Washington Wizards", abbreviation: "WAS", espnId: "27", conference: "East" },
] as const;

/** Primary brand color per team abbreviation */
export const TEAM_COLORS: Record<string, string> = {
  ATL: "#e03a3e",
  BOS: "#007a33",
  BKN: "#000000",
  CHA: "#1d1160",
  CHI: "#ce1141",
  CLE: "#860038",
  DAL: "#00538c",
  DEN: "#0e2240",
  DET: "#c8102e",
  GSW: "#1d428a",
  HOU: "#ce1141",
  IND: "#002d62",
  LAC: "#c8102e",
  LAL: "#552583",
  MEM: "#5d76a9",
  MIA: "#98002e",
  MIL: "#00471b",
  MIN: "#0c2340",
  NOP: "#0c2340",
  NYK: "#006bb6",
  OKC: "#007ac1",
  ORL: "#0077c0",
  PHI: "#006bb6",
  PHX: "#1d1160",
  POR: "#e03a3e",
  SAC: "#5a2d81",
  SAS: "#c4ced4",
  TOR: "#ce1141",
  UTA: "#002b5c",
  WAS: "#002b5c",
};
